### ISSUE TITLE
Setup perf test for Soroban traffic

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/supercluster#142]
Similar to our max TPS test for classic, we should create a separate test with Soroban or Soroban+Classic mix load, in order to evaluate performance.

**Comment by bboston7** [comment]
I'm thinking we should add a couple supercluster missions to support this:

* One mission runs a binary search for max TPS with the existing `soroban_invoke` `generateload` function.
  * Set parameters using real-world data from testnet+futurenet.
* One mission runs a binary search for max TPS using the `soroban_upload` `generateload` function.
  * Modify `soroban_upload` to take additional parameters specifying the underlying distribution wasms are sampled from. I need to look at the real-world testnet+futurenet data more closely to determine what the shape of the distribution for these parameters should be before I can decide on the parameters themselves.

The benefit of adding two new missions rather than augmenting the existing max TPS test to work over a blended set of transactions is that separate missions will make it easier to pinpoint where changes in performance are coming from.  The downside is that these missions will likely take a long time to run. However, I imagine we'd run them only as-needed (along side the current max TPS tests).

In both missions, we should make it easy to adjust the distribution parameters as we get more data from pubnet.

Does that all sound reasonable?

**Comment by marta-lokhova** [comment]
that makes sense! Perhaps we can add different "modes" to the existing max TPS missions to allow configuring it differently. That being said, I'd still recommend a version with mixed traffic as well, so we can get a sense of overall performance and to save time when trying to evaluate release candidates.

Seems like there are a few interesting questions we'd want to answer:
* What's a reasonable distribution of transaction sizes?
* What's a reasonable distribution of per-transaction resources? (instructions, disk reads and writes, etc). Related: current max TPS test is configured with simulated apply time to prevent noise from database backends. Simulating apply time with Soroban seems harder as there are a lot more variables to consider now. One option is to switch back to on-disk database; we can use BucketListDB, for example.

**Comment by bboston7** [comment]
> current max TPS test is configured with simulated apply time to prevent noise from database backends.

I can't quite figure out how this works. It looks like the max TPS test [configures simulated apply via `simulateApply{Duration, Weight}`](https://github.com/stellar/supercluster/blob/7d174050ae45319efce6c933545a214dc56b19d1/src/FSLibrary/MissionSimulatePubnetTier1Perf.fs#L25). The sleep time is set to `0`, so it doesn't actually sleep during apply time, but setting these [changes a few other values in stellar-core](https://github.com/stellar/stellar-core/blob/0f0c4d623a4866e86057c57db4b9c83018edd2b3/src/main/CommandLine.cpp#L1525). Does one of those settings result in a simulated apply?

**Comment by bboston7** [comment]
Here are some interesting histograms from futurenet:
![image](https://github.com/stellar/supercluster/assets/168167/97976a63-07e3-4153-b32f-6ce0c57ae78e)

The uniform distributions we're currently using in loadgen are pretty far from this! I think we could get closer by modeling these as lognormal distributions. That's still not perfect (the cpu instructions and bytes read histograms are bimodal), but it would be much closer.

Another option would be to use [`std::piecewise_constant_distribution`](https://en.cppreference.com/w/cpp/numeric/random/piecewise_constant_distribution) to model these more closely, at the expense of being more burdensome to specify.

**Comment by marta-lokhova** [comment]
> I can't quite figure out how this works. It looks like the max TPS test [configures simulated apply via simulateApply{Duration, Weight}](https://github.com/stellar/supercluster/blob/7d174050ae45319efce6c933545a214dc56b19d1/src/FSLibrary/MissionSimulatePubnetTier1Perf.fs#L25). The sleep time is set to 0, so it doesn't actually sleep during apply time, but setting these [changes a few other values in stellar-core](https://github.com/stellar/stellar-core/blob/0f0c4d623a4866e86057c57db4b9c83018edd2b3/src/main/CommandLine.cpp#L1525). Does one of those settings result in a simulated apply?

Ah yeah, it's a bit confusing. When in simulate mode, we still apply transactions, but to an in-memory sqlite database. Then, we add additional sleep to reach simulateApply time. Currently, we don't do that in Max TPS test (I think the initial idea was to test overlay only, so we set it to 0), but I think we should.
